# Generated by Django 5.2.4 on 2025-07-28 12:37

import advertisements.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa działu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dział',
                'verbose_name_plural': 'Działy',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa sklepu')),
                ('location', models.CharField(max_length=255, verbose_name='Lokalizacja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sklep',
                'verbose_name_plural': 'Sklepy',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa stoiska')),
                ('display_time', models.IntegerField(default=5, verbose_name='Czas wyświetlania (sekundy)')),
                ('transition_animation', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('flip', 'Flip'), ('none', 'None')], default='fade', max_length=20, verbose_name='Animacja przejścia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='advertisements.department', verbose_name='Dział')),
            ],
            options={
                'verbose_name': 'Stoisko',
                'verbose_name_plural': 'Stoiska',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('image', 'Obraz'), ('video', 'Film')], max_length=10, verbose_name='Typ materiału')),
                ('file', models.FileField(upload_to=advertisements.models.advertisement_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov'])], verbose_name='Plik')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('inactive', 'Nieaktywny')], default='active', max_length=10, verbose_name='Status')),
                ('duration', models.IntegerField(default=5, verbose_name='Czas wyświetlania (sekundy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='advertisements.stand', verbose_name='Stoisko')),
            ],
            options={
                'verbose_name': 'Materiał reklamowy',
                'verbose_name_plural': 'Materiały reklamowe',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='advertisements.store', verbose_name='Sklep'),
        ),
    ]
