# Generated by Django 5.2.4 on 2025-10-17 10:31

import advertisements.validators
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('image', 'Obraz'), ('video', 'Film')], max_length=10, verbose_name='Typ materiału')),
                ('file', cloudinary.models.CloudinaryField(help_text='Wybierz plik obrazu lub wideo. Obsługiwane formaty: jpg, jpeg, png, mp4, webm, mov, avi, mkv.', max_length=255, validators=[advertisements.validators.CloudinaryFileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'webm', 'mov', 'avi', 'mkv'], code='invalid_extension', message="Rozszerzenie pliku '%(extension)s' nie jest dozwolone. Dozwolone rozszerzenia: '%(allowed_extensions)s'.")], verbose_name='file')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wygaśnięcia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('inactive', 'Nieaktywny')], default='active', max_length=10, verbose_name='Status')),
                ('duration', models.IntegerField(default=5, verbose_name='Czas wyświetlania (sekundy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materiał reklamowy',
                'verbose_name_plural': 'Materiały reklamowe',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa działu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dział',
                'verbose_name_plural': 'Działy',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa sklepu')),
                ('location', models.CharField(max_length=255, verbose_name='Lokalizacja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sklep',
                'verbose_name_plural': 'Sklepy',
            },
        ),
        migrations.CreateModel(
            name='EmissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa harmonogramu')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('start_time', models.TimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.TimeField(verbose_name='Czas zakończenia')),
                ('repeat_type', models.CharField(choices=[('none', 'Bez powtarzania'), ('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc'), ('custom', 'Niestandardowy')], default='none', max_length=10, verbose_name='Typ powtarzania')),
                ('repeat_days', models.JSONField(blank=True, null=True, verbose_name='Dni powtarzania')),
                ('priority', models.IntegerField(default=5, verbose_name='Priorytet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materials', models.ManyToManyField(related_name='schedules', to='advertisements.advertisementmaterial', verbose_name='Materiały')),
            ],
            options={
                'verbose_name': 'Harmonogram emisji',
                'verbose_name_plural': 'Harmonogramy emisji',
                'ordering': ['-priority', 'start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa stoiska')),
                ('display_time', models.IntegerField(default=5, verbose_name='Czas wyświetlania (sekundy)')),
                ('transition_animation', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('flip', 'Flip'), ('none', 'None')], default='fade', max_length=20, verbose_name='Animacja przejścia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='advertisements.department', verbose_name='Dział')),
            ],
            options={
                'verbose_name': 'Stoisko',
                'verbose_name_plural': 'Stoiska',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Czy aktywny')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia aktywność')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rozdzielczość ekranu')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wersja odtwarzacza')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Błędy')),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_status', to='advertisements.stand', verbose_name='Stoisko')),
            ],
            options={
                'verbose_name': 'Status odtwarzacza',
                'verbose_name_plural': 'Statusy odtwarzaczy',
            },
        ),
        migrations.AddField(
            model_name='advertisementmaterial',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='advertisements.stand', verbose_name='Stoisko'),
        ),
        migrations.AddField(
            model_name='department',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='advertisements.store', verbose_name='Sklep'),
        ),
    ]
