# Generated by Django 5.2.4 on 2025-08-04 16:12

import advertisements.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmaterial',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Wybierz plik obrazu lub wideo. Obsługiwane formaty: jpg, jpeg, png, mp4, webm.', max_length=255, validators=[advertisements.validators.CloudinaryFileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'webm'], code='invalid_extension', message="Rozszerzenie pliku '%(extension)s' nie jest dozwolone. Dozwolone rozszerzenia: '%(allowed_extensions)s'.")], verbose_name='file'),
        ),
    ]
