# Generated by Django 5.2.4 on 2025-08-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmaterial',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wygaśnięcia'),
        ),
    ]
