# Generated by Django 5.2.4 on 2025-07-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Czy aktywny')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia aktywność')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rozdzielczość ekranu')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wersja odtwarzacza')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Błędy')),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_status', to='advertisements.stand', verbose_name='Stoisko')),
            ],
            options={
                'verbose_name': 'Status odtwarzacza',
                'verbose_name_plural': 'Statusy odtwarzaczy',
            },
        ),
    ]
