# Generated by Django 5.2.4 on 2025-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmaterial',
            name='cos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
