# Generated by Django 5.2.4 on 2025-12-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisementmaterial_cos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementmaterial',
            name='cos',
        ),
    ]
