# Generated by Django 5.2.4 on 2025-08-01 11:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_playerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmaterial',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
