# Generated by Django 5.2.4 on 2025-08-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisementmaterial_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa harmonogramu')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('start_time', models.TimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.TimeField(verbose_name='Czas zakończenia')),
                ('repeat_type', models.CharField(choices=[('none', 'Bez powtarzania'), ('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc'), ('custom', 'Niestandardowy')], default='none', max_length=10, verbose_name='Typ powtarzania')),
                ('repeat_days', models.JSONField(blank=True, help_text='Tablica dni tygodnia (0-6), gdy repeat_type=weekly', null=True, verbose_name='Dni powtarzania')),
                ('priority', models.IntegerField(default=5, help_text='Wyższy priorytet (10) wypiera niższy (1)', verbose_name='Priorytet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='advertisements.advertisementmaterial', verbose_name='Materiał')),
            ],
            options={
                'verbose_name': 'Harmonogram emisji',
                'verbose_name_plural': 'Harmonogramy emisji',
                'ordering': ['-priority', 'start_date', 'start_time'],
            },
        ),
    ]
