# Generated by Django 5.2.4 on 2025-08-01 11:46

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisementmaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmaterial',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Wybierz plik obrazu lub wideo. Obsługiwane formaty: jpg, jpeg, png, mp4, webm.', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'webm'])], verbose_name='file'),
        ),
    ]
