# Generated by Django 5.2.4 on 2025-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_emissionschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionschedule',
            name='material',
        ),
        migrations.AddField(
            model_name='emissionschedule',
            name='materials',
            field=models.ManyToManyField(related_name='schedules', to='advertisements.advertisementmaterial', verbose_name='Materiały'),
        ),
        migrations.AlterField(
            model_name='emissionschedule',
            name='priority',
            field=models.IntegerField(default=5, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='emissionschedule',
            name='repeat_days',
            field=models.JSONField(blank=True, null=True, verbose_name='Dni powtarzania'),
        ),
    ]
