# Generated by Django 5.2.4 on 2025-09-22 19:00

import advertisements.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisementmaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmaterial',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Wybierz plik obrazu lub wideo. Obsługiwane formaty: jpg, jpeg, png, mp4, webm, mov, avi, mkv.', max_length=255, validators=[advertisements.validators.CloudinaryFileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'webm', 'mov', 'avi', 'mkv'], code='invalid_extension', message="Rozszerzenie pliku '%(extension)s' nie jest dozwolone. Dozwolone rozszerzenia: '%(allowed_extensions)s'.")], verbose_name='file'),
        ),
    ]
